# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ../../drivers
  ];

  # Enable Intel Graphics Drivers
  drivers.intel.enable = true;

  boot.initrd.availableKernelModules = [
    "ehci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    "i915.enable_rc6=1"
    "i915.enable_fbc=1"
    "i915.fastboot=1"
    "video=SVIDEO-1:d"
    "snd_hda_intel.model=auto"
    "libata.noacpi=1"
  ];

  hardware.firmware = [
    (pkgs.writeTextDir "lib/firmware/hda-jack-retask.fw" ''
      [codec]
      0x10ec0662 0x00000000 2

      [pincfg]
      0x12 0x411111f0
      0x14 0x01014410
      0x15 0x411111f0
      0x16 0x411111f0
      0x18 0x01a19c30
      0x19 0x0321403f
      0x1a 0x0181343f
      0x1b 0x0221401f
      0x1c 0x411111f0
      0x1d 0x4004c601
      0x1e 0x01445120
    '')
  ];

  boot.extraModprobeConfig = ''
    options snd-hda-intel patch=hda-jack-retask.fw
  '';

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [
      "compress=zstd:1"
      "noatime"
      "discard=async"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-label/swap"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
